// Macros for server font, autogenerated from Python script
#define SERVER_PIXEL_HEIGHT       16

// Macros for channel font, autogenerated from Python script
#define CHANNEL_PIXEL_HEIGHT      18

// Macros for title font, autogenerated from Python script
#define TITLE_PIXEL_HEIGHT        26

// Macros for uname font, autogenerated from Python script
#define UNAME_PIXEL_HEIGHT        14

// Macros for message font, autogenerated from Python script
#define MESSAGE_PIXEL_HEIGHT      14
